version: '3.9'

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot_service
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./bot:/app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_service
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
